services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-documentserver
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      ALLOW_PRIVATE_IP_ADDRESS: "true"
      ALLOW_META_IP_ADDRESS: "true"
      JWT_ENABLED: "false"
